export let people = [
    { id: 1,
        dataAdresare: "19.10.2024",
        name: "Traci Serghei",
        dataNastere: "12.10.1985",
        city: "Cimislia",
        adress: "str. Cimislia 25",
        idnp: 22544545,
        trimitere: "Spitalizare",
        trimitereInstitutie: "Sr Cimislia",
        trimitereSpecialitate: "Chirurgier",
        trimitereSectie: "Chirurgie",
        trimitereData: "12.10.1985",
        tipInvestigatie: "RMN",
        rmn: "Creer cu contrast",
        tomografie: "",
        imunologie: [], //["Microalbuminei în urină", "Imunoglobulinei A"],
        hormoni: [], //["T3-liber prin metoda imunofluorescentă-fermentdependentă", "T4-liber  prin metoda imunofluorescentă-fermentdependentă"],
        oncologie: [], //["PSA total prin metoda imunofluoriscentă ferment dependent", "PSA-liber prin metoda imunofluoriscentă ferment dependent"],
        investigatieInstitutie: "Centrul Diagnostic Republican",
        dataInvestigatie: "19.10.2024",
        tipAnalize: "Imunologie",
        institutieAnalize: "", //"Centrul Diagnostic Republican",
        dataAnalize: "" //"19.10.2024"
    },
    { id: 2,
        dataAdresare: "19.10.2024",
        name: " Ou Andrei",
        dataNastere: "12.10.1985",
        city: "Basarabeasca",
        adress: "str. Decabal 36",
        idnp: 22544545,
        trimitere: "Consultatie",
        trimitereInstitutie: "Sr Cimislia",
        trimitereSpecialitate: "Chirurgier",
        trimitereSectie: "Chirurgie",
        trimitereData: "12.10.1985",
        tipInvestigatie: "RMN",
        rmn: "Coloana cervicala fara contrast",
        tomografie: "Tomografie Computerizata a creer",
        imunologie: [], // ["Microalbuminei în urină", "Imunoglobulinei A"],
        hormoni: [], // ["T3-liber prin metoda imunofluorescentă-fermentdependentă", "T4-liber  prin metoda imunofluorescentă-fermentdependentă"],
        oncologie: [], // ["PSA total prin metoda imunofluoriscentă ferment dependent", "PSA-liber prin metoda imunofluoriscentă ferment dependent"],
        investigatieInstitutie: "Centrul Diagnostic German",
        dataInvestigatie: "19.10.2024",
        tipAnalize: "Imunologie",
        institutieAnalize: "", // "Centrul Diagnostic Republican",
        dataAnalize: "" //"19.10.2024"
    },
    { id: 3,
        dataAdresare: "19.10.2024",
        name: "Traci Serghei",
        dataNastere: "12.10.1985",
        city: "Cimislia",
        adress: "str. Cimislia 25",
        idnp: 22544545,
        trimitere: "Spitalizare",
        trimitereInstitutie: "Sr Cimislia",
        trimitereSpecialitate: "Chirurgier",
        trimitereSectie: "Chirurgie",
        trimitereData: "12.10.1985",
        tipInvestigatie: "RMN",
        rmn: "Creer fara contrast",
        tomografie: "",
        imunologie: [], //["Microalbuminei în urină", "Imunoglobulinei A"],
        hormoni: [], //["T3-liber prin metoda imunofluorescentă-fermentdependentă", "T4-liber  prin metoda imunofluorescentă-fermentdependentă"],
        oncologie: [], //["PSA total prin metoda imunofluoriscentă ferment dependent", "PSA-liber prin metoda imunofluoriscentă ferment dependent"],
        investigatieInstitutie: "Centrul Diagnostic Republican",
        dataInvestigatie: "19.10.2024",
        tipAnalize: "Imunologie",
        institutieAnalize: "", //"Centrul Diagnostic Republican",
        dataAnalize: "" //"19.10.2024"
    },
];
//# sourceMappingURL=array.js.map